version: '3'

services:
  redis:
    image: redis:latest
    ports:
      - '6379:6379'
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - redis
    command: [ "pnpm", "run", "start" ]
    volumes:
      - .:/app
      - /app/node_modules
